name: RetroArch Minimal Builds
on:
  workflow_dispatch:
jobs:
  Windows:
    name: Build RetroArch Windows Minimal
    runs-on: windows-latest
    steps:
    - uses: msys2/setup-msys2@v2
      with:
        update: true
        install: >-
          base-devel
          git
          wget
          make
          mingw-w64-x86_64-toolchain
          mingw-w64-x86_64-ntldd
          mingw-w64-x86_64-zlib
          mingw-w64-x86_64-pkg-config
          mingw-w64-x86_64-freetype
          unzip
          p7zip
    - uses: actions/checkout@v3
    - name: Fetch the source
      run: git clone https://github.com/libretro/RetroArch.git
    - shell: msys2 {0}
      working-directory: RetroArch
      run: |
        ./configure --disable-qt --disable-ffmpeg --disable-sdl2
        make -j8
        for i in $(seq 3); do for bin in $(ntldd -R *exe | grep -i mingw | cut -d">" -f2 | cut -d" " -f2); do cp -vu "$bin" . ; done; done
        rm nvdaControllerClient64.dll
    - name: Strip exe
      working-directory: RetroArch
      run: strip.exe -s retroarch.exe
    - name: Zip just the executables and libs
      working-directory: RetroArch
      run: 7z a -mx=9 RetroArch-Win-x86_64-Minimal.7z *.exe *.dll
    - name: Upload Minimal 7z
      uses: svenstaro/upload-release-action@v2
      with:
        repo_token: ${{ secrets.GITHUB_TOKEN }}
        file: RetroArch/RetroArch-Win-x86_64-Minimal.7z
        tag: Main
        overwrite: true
    - shell: msys2 {0}
      working-directory: RetroArch
      run: |
        rm *.dll
    - shell: msys2 {0}
      working-directory: RetroArch
      run: |
        ./configure --disable-overlay --disable-networking --disable-video_filter --disable-glsl --disable-bsv_movie --disable-dsp_filter --disable-cheats --disable-rewind --disable-accessibility --disable-translate --disable-cdrom --disable-imageviewer --disable-qt --disable-ffmpeg --disable-sdl2 --disable-blissbox --disable-xmb --disable-materialui --disable-rgui --disable-d3d9 --disable-d3d10 --disable-wasapi --disable-libretrodb --disable-audiomixer --disable-dsound --disable-flac --disable-dr_mp3 --disable-rtga --disable-rjpeg --disable-rbmp --disable-freetype --disable-langextra --disable-cc_resampler --disable-nearest_resampler --disable-crtswitchres --disable-chd --disable-7zip --disable-patch
        make -j8
        for i in $(seq 3); do for bin in $(ntldd -R *exe | grep -i mingw | cut -d">" -f2 | cut -d" " -f2); do cp -vu "$bin" . ; done; done
    - name: Strip exe
      working-directory: RetroArch
      run: strip.exe -s retroarch.exe
    - name: Zip the exe and dlls
      working-directory: RetroArch
      run: 7z a -mx=9 RetroArch-Win-x86_64-Super_Minimal.7z *.exe *.dll
    - name: Upload Super Minimal 7z
      uses: svenstaro/upload-release-action@v2
      with:
        repo_token: ${{ secrets.GITHUB_TOKEN }}
        file: RetroArch/RetroArch-Win-x86_64-Super_Minimal.7z
        tag: Main
        overwrite: true
