name: RetroArch Minimal Builds
on:
  workflow_dispatch:
jobs:
  Windows:
    name: Build RetroArch Windows Minimal
    runs-on: windows-latest
    steps:
    - uses: msys2/setup-msys2@v2
      with:
        update: true
        install: >-
          base-devel
          git
          wget
          make
          mingw-w64-x86_64-toolchain
          mingw-w64-x86_64-ntldd
          mingw-w64-x86_64-zlib
          mingw-w64-x86_64-pkg-config
          mingw-w64-x86_64-freetype
          unzip
          p7zip
    - uses: actions/checkout@v3
    - name: Fetch the source
      run: git clone https://github.com/libretro/RetroArch.git
    - shell: msys2 {0}
      working-directory: RetroArch
      run: |
        ./configure --disable-qt --disable-ffmpeg
        make -j8
        for i in $(seq 3); do for bin in $(ntldd -R *exe | grep -i mingw | cut -d">" -f2 | cut -d" " -f2); do cp -vu "$bin" . ; done; done
        rm nvdaControllerClient64.dll
    - name: Strip exe
      working-directory: RetroArch
      run: strip.exe -s retroarch.exe
    - name: Zip just the executables and libs
      working-directory: RetroArch
      run: 7z a -mx=9 RetroArch-Win-x86_64-Minimal.7z *.exe *.dll
    - name: Upload Minimal 7z
      uses: svenstaro/upload-release-action@v2
      with:
        repo_token: ${{ secrets.GITHUB_TOKEN }}
        file: RetroArch/RetroArch-Win-x86_64-Minimal.7z
        tag: Main
        overwrite: true
 
